// categories
export const LOAD_CATEGORIES = 'LOAD_CATEGORIES'

// posts
export const LOAD_POSTS = 'LOAD_POSTS'
export const LOAD_CATEGORY_POSTS = 'LOAD_CATEGORY_POSTS'
export const SORT_POSTS = 'SORT_POSTS'

// post
export const LOAD_POST = 'LOAD_POST'
export const CREATE_POST = 'CREATE_POST'
export const VOTE_POST = 'VOTE_POST'
export const DELETE_POST = 'DELETE_POST'
export const RESET_POST = 'RESET_POST'
export const UPDATE_POST = 'UPDATE_POST'

// comments
export const LOAD_POST_COMMENTS = 'LOAD_POST_COMMENTS'
export const CREATE_POST_COMMENT = 'CREATE_POST_COMMENT'
export const EDIT_POST_COMMENT = 'EDIT_POST_COMMENT'
export const DELETE_POST_COMMENT = 'DELETE_POST_COMMENT'
export const VOTE_POST_COMMENT = 'VOTE_POST_COMMENT'
export const FETCH_NUM_COMMENTS = 'FETCH_NUM_COMMENTS'
export const FETCH_COMMENT = 'FETCH_COMMENT'